function [] = makeRunColorMap(data, scale)
lat = data(:,1);
lon = data(:,2);
col1 = data(:,9)/1000;
col2 = data(:,10)/1000;
col3 = data(:,11)/1000;
col4 = data(:,12)/1000;
col5 = data(:,13)/1000;
col6 = data(:,14)/1000;
noise = data(:,15)/1000;
figure;
hold on;
subplot(2, 3, 1);
makeColorMap(lat, lon, col1, noise, scale);
title('Collar 1');
colorbar;
subplot(2, 3, 2);
makeColorMap(lat, lon, col2, noise, scale);
title('Collar 2');
colorbar;
subplot(2, 3, 3);
makeColorMap(lat, lon, col3, noise, scale);
title('Collar 3');
colorbar;
subplot(2, 3, 4);
makeColorMap(lat, lon, col4, noise, scale);
title('Collar 4');
colorbar;
subplot(2, 3, 5);
makeColorMap(lat, lon, col5, noise, scale);
title('Collar 5');
colorbar;
subplot(2, 3, 6);
makeColorMap(lat, lon, col6, noise, scale);
title('Collar 6');
colorbar;
figure;
makeColorMap(lat, lon, noise, noise, scale);
title('Noise');
colorbar;
%clear lat lon col1 col2 col3 col4 col5 col6 noise
end